use winit::window::CursorIcon::*;

pub fn translate_cursor(cursor: vizia_core::CursorIcon) -> Option<winit::window::CursorIcon> {
    Some(match cursor {
        vizia_core::CursorIcon::Default => Default,
        vizia_core::CursorIcon::Crosshair => Crosshair,
        vizia_core::CursorIcon::Hand => Hand,
        vizia_core::CursorIcon::Arrow => Arrow,
        vizia_core::CursorIcon::Move => Move,
        vizia_core::CursorIcon::Text => Text,
        vizia_core::CursorIcon::Wait => Wait,
        vizia_core::CursorIcon::Help => Help,
        vizia_core::CursorIcon::Progress => Progress,
        vizia_core::CursorIcon::NotAllowed => NotAllowed,
        vizia_core::CursorIcon::ContextMenu => ContextMenu,
        vizia_core::CursorIcon::Cell => Cell,
        vizia_core::CursorIcon::VerticalText => VerticalText,
        vizia_core::CursorIcon::Alias => Alias,
        vizia_core::CursorIcon::Copy => Copy,
        vizia_core::CursorIcon::NoDrop => NoDrop,
        vizia_core::CursorIcon::Grab => Grab,
        vizia_core::CursorIcon::Grabbing => Grabbing,
        vizia_core::CursorIcon::AllScroll => AllScroll,
        vizia_core::CursorIcon::ZoomIn => ZoomIn,
        vizia_core::CursorIcon::ZoomOut => ZoomOut,
        vizia_core::CursorIcon::EResize => EResize,
        vizia_core::CursorIcon::NResize => NResize,
        vizia_core::CursorIcon::NeResize => NeResize,
        vizia_core::CursorIcon::NwResize => NwResize,
        vizia_core::CursorIcon::SResize => SResize,
        vizia_core::CursorIcon::SeResize => SeResize,
        vizia_core::CursorIcon::SwResize => SwResize,
        vizia_core::CursorIcon::WResize => WResize,
        vizia_core::CursorIcon::EwResize => EwResize,
        vizia_core::CursorIcon::NsResize => NsResize,
        vizia_core::CursorIcon::NeswResize => NeswResize,
        vizia_core::CursorIcon::NwseResize => NwseResize,
        vizia_core::CursorIcon::ColResize => ColResize,
        vizia_core::CursorIcon::RowResize => RowResize,
        vizia_core::CursorIcon::None => return None,
    })
}
