use std::fmt::Display;

use vizia::prelude::*;

#[derive(Debug, Data, Clone, Copy, PartialEq, Eq)]
pub enum Category {
    All,
    Latest,
    Animals,
    Arrows,
    Brand,
    Buildings,
    Charts,
    Communication,
    Computers,
    Currencies,
    Database,
    Design,
    Devices,
    Document,
    ECommerce,
    Electrical,
    Extensions,
    Filled,
    Food,
    Gender,
    Gestures,
    Health,
    Laundry,
    Letters,
    Logic,
    Map,
    Math,
    Media,
    Mood,
    Nature,
    Numbers,
    Photography,
    Shapes,
    Sport,
    Symbols,
    System,
    Text,
    Vehicles,
    VersionControl,
    Weather,
    Zodiac,
}

impl Display for Category {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let txt = match self {
            Category::All => "All",
            Category::Latest => "Latest",
            Category::Animals => "Animals",
            Category::Arrows => "Arrows",
            Category::Brand => "Brands",
            Category::Buildings => "Buildings",
            Category::Charts => "Charts",
            Category::Communication => "Communication",
            Category::Computers => "Computers",
            Category::Currencies => "Currencies",
            Category::Database => "Database",
            Category::Design => "Design",
            Category::Devices => "Devices",
            Category::Document => "Document",
            Category::ECommerce => "E-Commerce",
            Category::Electrical => "Electrical",
            Category::Extensions => "Extensions",
            Category::Filled => "Filled",
            Category::Food => "Food",
            Category::Gender => "Gender",
            Category::Gestures => "Gestures",
            Category::Health => "Health",
            Category::Laundry => "Laundry",
            Category::Letters => "Letters",
            Category::Logic => "Logic",
            Category::Map => "Map",
            Category::Math => "Math",
            Category::Media => "Media",
            Category::Mood => "Mood",
            Category::Nature => "Nature",
            Category::Numbers => "Numbers",
            Category::Photography => "Photography",
            Category::Shapes => "Shapes",
            Category::Sport => "Sport",
            Category::Symbols => "Symbols",
            Category::System => "System",
            Category::Text => "Text",
            Category::Vehicles => "Vehicles",
            Category::VersionControl => "Version Control",
            Category::Weather => "Weather",
            Category::Zodiac => "Zodiac",
        };

        f.write_str(txt)
    }
}
