name: Audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Runs at 15:00 UTC on Fri
    - cron: "0 15 * * 5"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: latest
      - run: rustup update
      - run: cargo audit --version
      # RUSTSEC-2024-0320: yaml-rust is unmaintained
      # RUSTSEC-2024-0436: paste is unmaintained
      - run: cargo audit --deny warnings --ignore RUSTSEC-2024-0320 --ignore RUSTSEC-2024-0436